# Generated by Django 6.0 on 2026-01-03 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0005_donor_total_donations_donor_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('Blood', 'Blood'), ('Organ', 'Organ')], max_length=10)),
                ('details', models.CharField(help_text='Blood group or organ type', max_length=100)),
                ('donated_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donor_app.donor')),
            ],
        ),
    ]
