# Generated by Django 6.0 on 2026-01-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0006_donationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='total_donations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
